# Generated by Django 5.2.13 on 2026-04-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_confession', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='confession',
            name='title',
            field=models.CharField(default='Untitled Confession', max_length=100),
        ),
    ]
